# Frontend Dockerfile
# ./frontend/Dockerfile
FROM node:23-alpine as build

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"] 