# docker-compose.dev.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5162
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5162:5162"
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=run.py
      - PORT=5162
      - DEBUG=True
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
    volumes:
      - ./backend:/app