services:
  # Backend service
  - type: web
    name: gohub
    env: docker
    plan: free
    rootDir: Backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: development
      - key: PORT
        value: 5162
      - key: GOOGLE_CLOUD_PROJECT
        value: flawless-snow-443501-q3
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /app/credentials/google-credentials.json
    healthCheckPath: /health

  # Frontend service
  - type: static
    name: gohub-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: Frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gohub.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
