services:
  - type: web
    name: gohub-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: NODE_VERSION
        value: 23.0.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health