services:
  - type: web
    name: gohub-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd Backend && gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: NODE_VERSION
        value: 23.0.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health


# Frontend service
  - type: static
    name: gohub-frontend
    buildCommand: cd Frontend && npm install && npm run build
    publishPath: Frontend/build
    # Add these specific static site settings
    routes:
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /register
        destination: /index.html
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /organizations
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
