# render.yaml
services:
  # Backend service
  - type: web
    name: gohub
    env: docker
    plan: free
    rootDir: Backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5162
      - key: DATABASE_URL
        fromService:
          type: postgresql
          name: gohub-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLOUD_PROJECT
        value: flawless-snow-443501-q3
      - key: GOOGLE_APPLICATION_CREDENTIALS
        fromFile: ./credentials/google-credentials.json
    healthCheckPath: /health
    disk:
      name: credentials
      mountPath: /app/credentials
      sizeGB: 1
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    preDeployCommand: python create_db.py

  # Frontend service
  - type: static
    name: gohub-frontend
    buildCommand: |
      cd Frontend
      npm install
      REACT_APP_API_URL=$RENDER_EXTERNAL_URL npm run build
    publishPath: Frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
