services:
  # Backend service
  - type: web
    name: gohub-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5162
    healthCheckPath: /api/health

  # Frontend service
  - type: web
    name: gohub-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: http://localhost:5162
