"""Initial migration

Revision ID: 6558698f13fe
Revises: 
Create Date: 2024-12-27 16:02:17.986405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6558698f13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_link')
    op.drop_table('mpesa_config')
    with op.batch_alter_table('org_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_logo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_cover_photo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_physical_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('org_google_maps_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('org_facebook', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_x', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_instagram', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_youtube', sa.String(length=200), nullable=True))
        batch_op.drop_column('org_logo')
        batch_op.drop_column('org_cover_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_cover_photo', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_logo', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('org_youtube')
        batch_op.drop_column('org_linkedin')
        batch_op.drop_column('org_instagram')
        batch_op.drop_column('org_x')
        batch_op.drop_column('org_facebook')
        batch_op.drop_column('org_google_maps_link')
        batch_op.drop_column('org_physical_description')
        batch_op.drop_column('org_cover_photo_filename')
        batch_op.drop_column('org_logo_filename')

    op.create_table('mpesa_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('org_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('merchant_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_profile_id'], ['org_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_profile_id')
    )
    op.create_table('social_media_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.INTEGER(), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=200), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
