"""update_cloudsql_to_match_local

Revision ID: dc8b189a250c
Revises: dc151b9e439f
Create Date: 2025-01-27 14:57:47.913774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8b189a250c'
down_revision = 'dc151b9e439f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_link')
    with op.batch_alter_table('org_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_logo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_cover_photo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_physical_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('org_google_maps_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('org_facebook', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_x', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_instagram', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('org_youtube', sa.String(length=200), nullable=True))
        batch_op.drop_column('org_cover_photo')
        batch_op.drop_column('org_logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_logo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('org_cover_photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('org_youtube')
        batch_op.drop_column('org_linkedin')
        batch_op.drop_column('org_instagram')
        batch_op.drop_column('org_x')
        batch_op.drop_column('org_facebook')
        batch_op.drop_column('org_google_maps_link')
        batch_op.drop_column('org_physical_description')
        batch_op.drop_column('org_cover_photo_filename')
        batch_op.drop_column('org_logo_filename')

    op.create_table('social_media_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org_profile.id'], name='social_media_link_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_media_link_pkey')
    )
    # ### end Alembic commands ###
