name: Database Migrations

on:
  workflow_dispatch:
  push:
    branches:
      - deployment
    paths:
      - 'Backend/migrations/**'
      - 'Backend/models/**'
      - '.github/workflows/cloudsql-migrate.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup GCP Credentials
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-credentials.json
          chmod 600 gcp-credentials.json

      - name: Install and start Cloud SQL Proxy v2
        run: |
          # Download Cloud SQL Proxy v2
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.1/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          
          # Start the proxy with verbose logging
          ./cloud-sql-proxy \
            --credentials-file=gcp-credentials.json \
            --address 0.0.0.0 \
            --port 5432 \
            gohub-92b6b:us-west1:ngo-connect-db &
          
          # Wait for proxy to start and verify it's running
          sleep 10
          ps aux | grep cloud-sql-proxy
          netstat -tlpn | grep 5432 || ss -tlpn | grep 5432

      # Install dependencies first
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary
          cd Backend && pip install -r requirements.dev.txt

      - name: Test Database Connection
        run: |
          # Wait a bit more for the proxy to be fully ready
          sleep 5
          python -c "
          import psycopg2
          import time
          max_attempts = 3
          for attempt in range(max_attempts):
              try:
                  print(f'Attempt {attempt + 1} to connect to database...')
                  conn = psycopg2.connect(
                      dbname='ngo_connect',
                      user='postgres',
                      password='${{ secrets.DB_PASSWORD }}',
                      host='127.0.0.1',
                      port='5432'
                  )
                  print('Database connection successful!')
                  conn.close()
                  break
              except Exception as e:
                  print(f'Connection attempt {attempt + 1} failed: {e}')
                  if attempt < max_attempts - 1:
                      print('Waiting 5 seconds before retrying...')
                      time.sleep(5)
                  else:
                      print('All connection attempts failed')
                      exit(1)
          "

      - name: Run Database Migrations
        working-directory: Backend
        env:
          FLASK_APP: "app:create_app()"
          DATABASE_URL: "postgresql://postgres:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/ngo_connect"
        run: |
          echo "Running migrations..."
          python manage_db.py

      - name: Stop Cloud SQL Proxy
        if: always()
        run: |
          pkill cloud-sql-proxy || true

      - name: Cleanup
        if: always()
        run: |
          rm -f gcp-credentials.json