name: Database Migrations

on:
  workflow_dispatch:
  push:
    branches:
      - deployment
    paths:
      - 'Backend/migrations/**'
      - 'Backend/models/**'
      - '.github/workflows/cloudsql-migrate.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: gohub-92b6b

      - name: Start Cloud SQL Proxy
        run: |
          ./cloud_sql_proxy gohub-92b6b:us-west1:ngo-connect-db &
          # Wait for proxy to start
          sleep 5

      - name: Install dependencies
        working-directory: Backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          
      - name: Debug Python Environment
        working-directory: Backend
        run: |
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Run Database Migrations
        working-directory: Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FLASK_APP: ${{ secrets.FLASK_APP }}
          PYTHONPATH: ${PYTHONPATH}:${GITHUB_WORKSPACE}/Backend
        run: |
          python manage_db.py

      - name: Stop Cloud SQL Proxy
        if: always()
        run: |
          pkill cloud_sql_proxy || true