name: Sync main to deployment

on:
    push:
        branches:
        - main

jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configure Git
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
        
        - name: Sync deployment branch
          run: |
            # Fetch all branches
            git fetch origin
            
            # Check if deployment branch exists
            if git show-ref --verify --quiet refs/remotes/origin/deployment; then
                echo "Deployment branch exists, syncing..."
                git checkout deployment
                git pull origin deployment
                git merge origin/main --no-edit
                git push origin deployment
            else
                echo "Creating deployment branch..."
                git checkout -b deployment
                git push -u origin deployment
            fi